"""
RiskAssessment ORM model.

The risk score is calculated by the Python risk engine — NOT by the LLM.
The LLM generates only the score_explanation text.

score_breakdown stores the full transparent calculation:
  {
    "base_score": 50,
    "factors": [
      {"name": "loss_trend", "delta": +15, "reason": "Severity increasing YoY"},
      {"name": "revenue_discrepancy", "delta": +10, "reason": "ACORD vs FS mismatch"},
      {"name": "missing_information", "delta": +5, "reason": "3 required fields absent"},
      {"name": "stable_financials", "delta": -5, "reason": "No major financial changes"}
    ],
    "final_score": 75,
    "category": "HIGH",
    "thresholds_used": {"low_max": 39, "medium_max": 69, "high_min": 70},
    "threshold_source": "DEMO RULE — NOT APPROVED POLICY"
  }

This transparency allows underwriters to understand exactly why the score
was assigned, and to challenge any factor they disagree with.
"""
from __future__ import annotations

import uuid

from sqlalchemy import Float, ForeignKey, Index, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSON, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.constants import RiskCategory
from app.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin


class RiskAssessment(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = "risk_assessments"

    __table_args__ = (
        Index("ix_risk_assessments_submission_id", "submission_id"),
    )

    submission_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("submissions.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        comment="One risk assessment per submission",
    )

    # -------------------------------------------------------------------------
    # Score — calculated by Python, not LLM
    # -------------------------------------------------------------------------
    risk_score: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
        comment="0–100. Null if insufficient data to calculate.",
    )
    risk_category: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default=RiskCategory.UNDETERMINED.value,
        comment="LOW | MEDIUM | HIGH | UNDETERMINED",
    )
    score_breakdown: Mapped[dict | None] = mapped_column(
        JSON,
        nullable=True,
        comment="Full transparent calculation showing each factor and its contribution",
    )

    # -------------------------------------------------------------------------
    # Explanation — generated by LLM, clearly labelled as AI output
    # -------------------------------------------------------------------------
    score_explanation: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="LLM-generated explanation of the risk score in underwriting language",
    )
    ai_recommendation: Mapped[str | None] = mapped_column(
        String(50),
        nullable=True,
        comment="AI suggestion for the underwriter — NOT a final decision",
    )
    ai_recommendation_rationale: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Evidence-supported rationale for the AI recommendation",
    )

    # -------------------------------------------------------------------------
    # Metadata
    # -------------------------------------------------------------------------
    calculated_by_model: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        comment="LLM model used for explanation generation",
    )
    confidence: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        comment="Overall confidence in the assessment 0.0–1.0",
    )

    def __repr__(self) -> str:
        return (
            f"<RiskAssessment score={self.risk_score} "
            f"category={self.risk_category!r}>"
        )
